###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grapqh-sample?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 11dbstkd
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
